<?php

namespace Database\Seeders;

use App\Models\Municipio;
use Illuminate\Database\Seeder;

class MunicipiosTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        $municipios = [
            ['departamento_id' => 1, 'codigo' => 1, 'nombre' => 'Medellin'],
            ['departamento_id' => 1, 'codigo' => 2, 'nombre' => 'ABEJORRAL'],
            ['departamento_id' => 1, 'codigo' => 4, 'nombre' => 'ABRIAQUI'],
            ['departamento_id' => 1, 'codigo' => 21, 'nombre' => 'ALEJANDRIA'],
            ['departamento_id' => 1, 'codigo' => 30, 'nombre' => 'AMAGA'],
            ['departamento_id' => 1, 'codigo' => 31, 'nombre' => 'AMALFI'],
            ['departamento_id' => 1, 'codigo' => 34, 'nombre' => 'ANDES'],
            ['departamento_id' => 1, 'codigo' => 36, 'nombre' => 'ANGELOPOLIS'],
            ['departamento_id' => 1, 'codigo' => 38, 'nombre' => 'ANGOSTURA'],
            ['departamento_id' => 1, 'codigo' => 40, 'nombre' => 'ANORI'],
            ['departamento_id' => 1, 'codigo' => 42, 'nombre' => 'ANTIOQUIA'],
            ['departamento_id' => 1, 'codigo' => 44, 'nombre' => 'ANZA'],
            ['departamento_id' => 1, 'codigo' => 45, 'nombre' => 'APARTADO'],
            ['departamento_id' => 1, 'codigo' => 51, 'nombre' => 'ARBOLETES'],
            ['departamento_id' => 1, 'codigo' => 55, 'nombre' => 'ARGELIA'],
            ['departamento_id' => 1, 'codigo' => 59, 'nombre' => 'ARMENIA'],
            ['departamento_id' => 1, 'codigo' => 79, 'nombre' => 'BARBOSA'],
            ['departamento_id' => 1, 'codigo' => 86, 'nombre' => 'BELMIRA'],
            ['departamento_id' => 1, 'codigo' => 88, 'nombre' => 'BELLO'],
            ['departamento_id' => 1, 'codigo' => 91, 'nombre' => 'BETANIA'],
            ['departamento_id' => 1, 'codigo' => 93, 'nombre' => 'BETULIA'],
            ['departamento_id' => 1, 'codigo' => 101, 'nombre' => 'BOLIVAR'],
            ['departamento_id' => 1, 'codigo' => 107, 'nombre' => 'BRICEÑO'],
            ['departamento_id' => 1, 'codigo' => 113, 'nombre' => 'BURITICA'],
            ['departamento_id' => 1, 'codigo' => 120, 'nombre' => 'CACERES'],
            ['departamento_id' => 1, 'codigo' => 125, 'nombre' => 'CAICEDO'],
            ['departamento_id' => 1, 'codigo' => 129, 'nombre' => 'CALDAS'],
            ['departamento_id' => 1, 'codigo' => 134, 'nombre' => 'CAMPAMENTO'],
            ['departamento_id' => 1, 'codigo' => 138, 'nombre' => 'CAÑASGORDAS'],
            ['departamento_id' => 1, 'codigo' => 142, 'nombre' => 'CARACOLI'],
            ['departamento_id' => 1, 'codigo' => 145, 'nombre' => 'CARAMANTA'],
            ['departamento_id' => 1, 'codigo' => 147, 'nombre' => 'CAREPA'],
            ['departamento_id' => 1, 'codigo' => 148, 'nombre' => 'CARMEN DE VIBORAL'],
            ['departamento_id' => 1, 'codigo' => 150, 'nombre' => 'CAROLINA'],
            ['departamento_id' => 1, 'codigo' => 154, 'nombre' => 'CAUCASIA'],
            ['departamento_id' => 1, 'codigo' => 172, 'nombre' => 'CHIGORODO'],
            ['departamento_id' => 1, 'codigo' => 190, 'nombre' => 'CISNEROS'],
            ['departamento_id' => 1, 'codigo' => 197, 'nombre' => 'COCORNA'],
            ['departamento_id' => 1, 'codigo' => 206, 'nombre' => 'CONCEPCION'],
            ['departamento_id' => 1, 'codigo' => 209, 'nombre' => 'CONCORDIA'],
            ['departamento_id' => 1, 'codigo' => 212, 'nombre' => 'COPACABANA'],
            ['departamento_id' => 1, 'codigo' => 234, 'nombre' => 'DABEIBA'],
            ['departamento_id' => 1, 'codigo' => 237, 'nombre' => 'DON MATIAS'],
            ['departamento_id' => 1, 'codigo' => 240, 'nombre' => 'EBEJICO'],
            ['departamento_id' => 1, 'codigo' => 250, 'nombre' => 'EL BAGRE'],
            ['departamento_id' => 1, 'codigo' => 264, 'nombre' => 'ENTRERRIOS'],
            ['departamento_id' => 1, 'codigo' => 266, 'nombre' => 'ENVIGADO'],
            ['departamento_id' => 1, 'codigo' => 282, 'nombre' => 'FREDONIA'],
            ['departamento_id' => 1, 'codigo' => 284, 'nombre' => 'FRONTINO'],
            ['departamento_id' => 1, 'codigo' => 306, 'nombre' => 'GIRALDO'],
            ['departamento_id' => 1, 'codigo' => 308, 'nombre' => 'GIRARDOTA'],
            ['departamento_id' => 1, 'codigo' => 310, 'nombre' => 'GOMEZ PLATA'],
            ['departamento_id' => 1, 'codigo' => 313, 'nombre' => 'GRANADA'],
            ['departamento_id' => 1, 'codigo' => 315, 'nombre' => 'GUADALUPE'],
            ['departamento_id' => 1, 'codigo' => 318, 'nombre' => 'GUARNE'],
            ['departamento_id' => 1, 'codigo' => 321, 'nombre' => 'GUATAPE'],
            ['departamento_id' => 1, 'codigo' => 347, 'nombre' => 'HELICONIA'],
            ['departamento_id' => 1, 'codigo' => 353, 'nombre' => 'HISPANIA'],
            ['departamento_id' => 1, 'codigo' => 360, 'nombre' => 'ITAGUI'],
            ['departamento_id' => 1, 'codigo' => 361, 'nombre' => 'ITUANGO'],
            ['departamento_id' => 1, 'codigo' => 364, 'nombre' => 'JARDIN'],
            ['departamento_id' => 1, 'codigo' => 368, 'nombre' => 'JERICO'],
            ['departamento_id' => 1, 'codigo' => 376, 'nombre' => 'LA CEJA'],
            ['departamento_id' => 1, 'codigo' => 380, 'nombre' => 'LA ESTRELLA'],
            ['departamento_id' => 1, 'codigo' => 390, 'nombre' => 'LA PINTADA'],
            ['departamento_id' => 1, 'codigo' => 400, 'nombre' => 'LA UNION'],
            ['departamento_id' => 1, 'codigo' => 411, 'nombre' => 'LIBORINA'],
            ['departamento_id' => 1, 'codigo' => 425, 'nombre' => 'MACEO'],
            ['departamento_id' => 1, 'codigo' => 440, 'nombre' => 'MARINILLA'],
            ['departamento_id' => 1, 'codigo' => 467, 'nombre' => 'MONTEBELLO'],
            ['departamento_id' => 1, 'codigo' => 475, 'nombre' => 'MURINDO'],
            ['departamento_id' => 1, 'codigo' => 480, 'nombre' => 'MUTATA'],
            ['departamento_id' => 1, 'codigo' => 483, 'nombre' => 'NARIÑO'],
            ['departamento_id' => 1, 'codigo' => 490, 'nombre' => 'NECOCLI'],
            ['departamento_id' => 1, 'codigo' => 495, 'nombre' => 'NECHI'],
            ['departamento_id' => 1, 'codigo' => 501, 'nombre' => 'OLAYA'],
            ['departamento_id' => 1, 'codigo' => 541, 'nombre' => 'PEÑOL'],
            ['departamento_id' => 1, 'codigo' => 543, 'nombre' => 'PEQUE'],
            ['departamento_id' => 1, 'codigo' => 576, 'nombre' => 'PUEBLORRICO'],
            ['departamento_id' => 1, 'codigo' => 579, 'nombre' => 'PUERTO BERRIO'],
            ['departamento_id' => 1, 'codigo' => 585, 'nombre' => 'PUERTO NARE (LA MAGDALENA)'],
            ['departamento_id' => 1, 'codigo' => 591, 'nombre' => 'PUERTO TRIUNFO'],
            ['departamento_id' => 1, 'codigo' => 604, 'nombre' => 'REMEDIOS'],
            ['departamento_id' => 1, 'codigo' => 607, 'nombre' => 'RETIRO'],
            ['departamento_id' => 1, 'codigo' => 615, 'nombre' => 'RIONEGRO'],
            ['departamento_id' => 1, 'codigo' => 628, 'nombre' => 'SABANALARGA'],
            ['departamento_id' => 1, 'codigo' => 631, 'nombre' => 'SABANETA'],
            ['departamento_id' => 1, 'codigo' => 642, 'nombre' => 'SALGAR'],
            ['departamento_id' => 1, 'codigo' => 647, 'nombre' => 'SAN ANDRES'],
            ['departamento_id' => 1, 'codigo' => 649, 'nombre' => 'SAN CARLOS'],
            ['departamento_id' => 1, 'codigo' => 652, 'nombre' => 'SAN FRANCISCO'],
            ['departamento_id' => 1, 'codigo' => 656, 'nombre' => 'SAN JERONIMO'],
            ['departamento_id' => 1, 'codigo' => 658, 'nombre' => 'SAN JOSE DE LA MONTAÑA'],
            ['departamento_id' => 1, 'codigo' => 659, 'nombre' => 'SAN JUAN DE URABA'],
            ['departamento_id' => 1, 'codigo' => 660, 'nombre' => 'SAN LUIS'],
            ['departamento_id' => 1, 'codigo' => 664, 'nombre' => 'SAN PEDRO'],
            ['departamento_id' => 1, 'codigo' => 665, 'nombre' => 'SAN PEDRO DE URABA'],
            ['departamento_id' => 1, 'codigo' => 667, 'nombre' => 'SAN RAFAEL'],
            ['departamento_id' => 1, 'codigo' => 670, 'nombre' => 'SAN ROQUE'],
            ['departamento_id' => 1, 'codigo' => 674, 'nombre' => 'SAN VICENTE'],
            ['departamento_id' => 1, 'codigo' => 679, 'nombre' => 'SANTA BARBARA'],
            ['departamento_id' => 1, 'codigo' => 686, 'nombre' => 'SANTA ROSA DE OSOS'],
            ['departamento_id' => 1, 'codigo' => 690, 'nombre' => 'SANTO DOMINGO'],
            ['departamento_id' => 1, 'codigo' => 697, 'nombre' => 'SANTUARIO'],
            ['departamento_id' => 1, 'codigo' => 736, 'nombre' => 'SEGOVIA'],
            ['departamento_id' => 1, 'codigo' => 756, 'nombre' => 'SONSON'],
            ['departamento_id' => 1, 'codigo' => 761, 'nombre' => 'SOPETRAN'],
            ['departamento_id' => 1, 'codigo' => 789, 'nombre' => 'TAMESIS'],
            ['departamento_id' => 1, 'codigo' => 790, 'nombre' => 'TARAZA'],
            ['departamento_id' => 1, 'codigo' => 792, 'nombre' => 'TARSO'],
            ['departamento_id' => 1, 'codigo' => 809, 'nombre' => 'TITIRIBI'],
            ['departamento_id' => 1, 'codigo' => 819, 'nombre' => 'TOLEDO'],
            ['departamento_id' => 1, 'codigo' => 837, 'nombre' => 'TURBO'],
            ['departamento_id' => 1, 'codigo' => 842, 'nombre' => 'URAMITA'],
            ['departamento_id' => 1, 'codigo' => 847, 'nombre' => 'URRAO'],
            ['departamento_id' => 1, 'codigo' => 854, 'nombre' => 'VALDIVIA'],
            ['departamento_id' => 1, 'codigo' => 856, 'nombre' => 'VALPARAISO'],
            ['departamento_id' => 1, 'codigo' => 858, 'nombre' => 'VEGACHI'],
            ['departamento_id' => 1, 'codigo' => 861, 'nombre' => 'VENECIA'],
            ['departamento_id' => 1, 'codigo' => 873, 'nombre' => 'VIGIA DEL FUERTE'],
            ['departamento_id' => 1, 'codigo' => 885, 'nombre' => 'YALI'],
            ['departamento_id' => 1, 'codigo' => 887, 'nombre' => 'YARUMAL'],
            ['departamento_id' => 1, 'codigo' => 890, 'nombre' => 'YOLOMBO'],
            ['departamento_id' => 1, 'codigo' => 893, 'nombre' => 'YONDO'],
            ['departamento_id' => 1, 'codigo' => 895, 'nombre' => 'ZARAGOZA'],
            ['departamento_id' => 2, 'codigo' => 1, 'nombre' => 'BARRANQUILLA (DISTRITO ESPECIAL INDUSTRIAL Y PORTUARIO DE BARRANQUILLA)'],
            ['departamento_id' => 2, 'codigo' => 78, 'nombre' => 'BARANOA'],
            ['departamento_id' => 2, 'codigo' => 137, 'nombre' => 'CAMPO DE LA CRUZ'],
            ['departamento_id' => 2, 'codigo' => 141, 'nombre' => 'CANDELARIA'],
            ['departamento_id' => 2, 'codigo' => 296, 'nombre' => 'GALAPA'],
            ['departamento_id' => 2, 'codigo' => 372, 'nombre' => 'JUAN DE ACOSTA'],
            ['departamento_id' => 2, 'codigo' => 421, 'nombre' => 'LURUACO'],
            ['departamento_id' => 2, 'codigo' => 433, 'nombre' => 'MALAMBO'],
            ['departamento_id' => 2, 'codigo' => 436, 'nombre' => 'MANATI'],
            ['departamento_id' => 2, 'codigo' => 520, 'nombre' => 'PALMAR DE VARELA'],
            ['departamento_id' => 2, 'codigo' => 549, 'nombre' => 'PIOJO'],
            ['departamento_id' => 2, 'codigo' => 558, 'nombre' => 'POLO NUEVO'],
            ['departamento_id' => 2, 'codigo' => 560, 'nombre' => 'PONEDERA'],
            ['departamento_id' => 2, 'codigo' => 573, 'nombre' => 'PUERTO COLOMBIA'],
            ['departamento_id' => 2, 'codigo' => 606, 'nombre' => 'REPELON'],
            ['departamento_id' => 2, 'codigo' => 634, 'nombre' => 'SABANAGRANDE'],
            ['departamento_id' => 2, 'codigo' => 638, 'nombre' => 'SABANALARGA'],
            ['departamento_id' => 2, 'codigo' => 675, 'nombre' => 'SANTA LUCIA'],
            ['departamento_id' => 2, 'codigo' => 685, 'nombre' => 'SANTO TOMAS'],
            ['departamento_id' => 2, 'codigo' => 758, 'nombre' => 'SOLEDAD'],
            ['departamento_id' => 2, 'codigo' => 770, 'nombre' => 'SUAN'],
            ['departamento_id' => 2, 'codigo' => 832, 'nombre' => 'TUBARA'],
            ['departamento_id' => 2, 'codigo' => 849, 'nombre' => 'USIACURI'],
            ['departamento_id' => 3, 'codigo' => 1, 'nombre' => 'Santa Fe de Bogotá'],
            ['departamento_id' => 3, 'codigo' => 1, 'nombre' => 'USAQUEN'],
            ['departamento_id' => 3, 'codigo' => 2, 'nombre' => 'CHAPINERO'],
            ['departamento_id' => 3, 'codigo' => 3, 'nombre' => 'SANTA FE'],
            ['departamento_id' => 3, 'codigo' => 4, 'nombre' => 'SAN CRISTOBAL'],
            ['departamento_id' => 3, 'codigo' => 5, 'nombre' => 'USME'],
            ['departamento_id' => 3, 'codigo' => 6, 'nombre' => 'TUNJUELITO'],
            ['departamento_id' => 3, 'codigo' => 7, 'nombre' => 'BOSA'],
            ['departamento_id' => 3, 'codigo' => 8, 'nombre' => 'KENNEDY'],
            ['departamento_id' => 3, 'codigo' => 9, 'nombre' => 'FONTIBON'],
            ['departamento_id' => 3, 'codigo' => 10, 'nombre' => 'ENGATIVA'],
            ['departamento_id' => 3, 'codigo' => 11, 'nombre' => 'SUBA'],
            ['departamento_id' => 3, 'codigo' => 12, 'nombre' => 'BARRIOS UNIDOS'],
            ['departamento_id' => 3, 'codigo' => 13, 'nombre' => 'TEUSAQUILLO'],
            ['departamento_id' => 3, 'codigo' => 14, 'nombre' => 'MARTIRES'],
            ['departamento_id' => 3, 'codigo' => 15, 'nombre' => 'ANTONIO NARIÑO'],
            ['departamento_id' => 3, 'codigo' => 16, 'nombre' => 'PUENTE ARANDA'],
            ['departamento_id' => 3, 'codigo' => 17, 'nombre' => 'CANDELARIA'],
            ['departamento_id' => 3, 'codigo' => 18, 'nombre' => 'RAFAEL URIBE'],
            ['departamento_id' => 3, 'codigo' => 19, 'nombre' => 'CIUDAD BOLIVAR'],
            ['departamento_id' => 3, 'codigo' => 20, 'nombre' => 'SUMAPAZ'],
            ['departamento_id' => 4, 'codigo' => 1, 'nombre' => 'CARTAGENA (DISTRITO TURISTICO Y CULTURAL DE CARTAGENA)'],
            ['departamento_id' => 4, 'codigo' => 6, 'nombre' => 'ACHI'],
            ['departamento_id' => 4, 'codigo' => 30, 'nombre' => 'ALTOS DEL ROSARIO'],
            ['departamento_id' => 4, 'codigo' => 42, 'nombre' => 'ARENAL'],
            ['departamento_id' => 4, 'codigo' => 52, 'nombre' => 'ARJONA'],
            ['departamento_id' => 4, 'codigo' => 62, 'nombre' => 'ARROYOHONDO'],
            ['departamento_id' => 4, 'codigo' => 74, 'nombre' => 'BARRANCO DE LOBA'],
            ['departamento_id' => 4, 'codigo' => 140, 'nombre' => 'CALAMAR'],
            ['departamento_id' => 4, 'codigo' => 160, 'nombre' => 'CANTAGALLO'],
            ['departamento_id' => 4, 'codigo' => 188, 'nombre' => 'CICUCO'],
            ['departamento_id' => 4, 'codigo' => 212, 'nombre' => 'CORDOBA'],
            ['departamento_id' => 4, 'codigo' => 222, 'nombre' => 'CLEMENCIA'],
            ['departamento_id' => 4, 'codigo' => 244, 'nombre' => 'EL CARMEN DE BOLIVAR'],
            ['departamento_id' => 4, 'codigo' => 248, 'nombre' => 'EL GUAMO'],
            ['departamento_id' => 4, 'codigo' => 268, 'nombre' => 'EL PEÑON'],
            ['departamento_id' => 4, 'codigo' => 300, 'nombre' => 'HATILLO DE LOBA'],
            ['departamento_id' => 4, 'codigo' => 430, 'nombre' => 'MAGANGUE'],
            ['departamento_id' => 4, 'codigo' => 433, 'nombre' => 'MAHATES'],
            ['departamento_id' => 4, 'codigo' => 440, 'nombre' => 'MARGARITA'],
            ['departamento_id' => 4, 'codigo' => 442, 'nombre' => 'MARIA LA BAJA'],
            ['departamento_id' => 4, 'codigo' => 458, 'nombre' => 'MONTECRISTO'],
            ['departamento_id' => 4, 'codigo' => 468, 'nombre' => 'MOMPOS'],
            ['departamento_id' => 4, 'codigo' => 473, 'nombre' => 'MORALES'],
            ['departamento_id' => 4, 'codigo' => 549, 'nombre' => 'PINILLOS'],
            ['departamento_id' => 4, 'codigo' => 580, 'nombre' => 'REGIDOR'],
            ['departamento_id' => 4, 'codigo' => 600, 'nombre' => 'RIO VIEJO'],
            ['departamento_id' => 4, 'codigo' => 620, 'nombre' => 'SAN CRISTOBAL'],
            ['departamento_id' => 4, 'codigo' => 647, 'nombre' => 'SAN ESTANISLAO'],
            ['departamento_id' => 4, 'codigo' => 650, 'nombre' => 'SAN FERNANDO'],
            ['departamento_id' => 4, 'codigo' => 654, 'nombre' => 'SAN JACINTO'],
            ['departamento_id' => 4, 'codigo' => 655, 'nombre' => 'SAN JACINTO DEL CAUCA'],
            ['departamento_id' => 4, 'codigo' => 657, 'nombre' => 'SAN JUAN NEPOMUCENO'],
            ['departamento_id' => 4, 'codigo' => 667, 'nombre' => 'SAN MARTIN DE LOBA'],
            ['departamento_id' => 4, 'codigo' => 670, 'nombre' => 'SAN PABLO'],
            ['departamento_id' => 4, 'codigo' => 673, 'nombre' => 'SANTA CATALINA'],
            ['departamento_id' => 4, 'codigo' => 683, 'nombre' => 'SANTA ROSA'],
            ['departamento_id' => 4, 'codigo' => 688, 'nombre' => 'SANTA ROSA DEL SUR'],
            ['departamento_id' => 4, 'codigo' => 744, 'nombre' => 'SIMITI'],
            ['departamento_id' => 4, 'codigo' => 760, 'nombre' => 'SOPLAVIENTO'],
            ['departamento_id' => 4, 'codigo' => 780, 'nombre' => 'TALAIGUA NUEVO'],
            ['departamento_id' => 4, 'codigo' => 810, 'nombre' => 'TIQUISIO (PUERTO RICO)'],
            ['departamento_id' => 4, 'codigo' => 836, 'nombre' => 'TURBACO'],
            ['departamento_id' => 4, 'codigo' => 838, 'nombre' => 'TURBANA'],
            ['departamento_id' => 4, 'codigo' => 873, 'nombre' => 'VILLANUEVA'],
            ['departamento_id' => 4, 'codigo' => 894, 'nombre' => 'ZAMBRANO'],
            ['departamento_id' => 5, 'codigo' => 1, 'nombre' => 'TUNJA'],
            ['departamento_id' => 5, 'codigo' => 22, 'nombre' => 'ALMEIDA'],
            ['departamento_id' => 5, 'codigo' => 47, 'nombre' => 'AQUITANIA'],
            ['departamento_id' => 5, 'codigo' => 51, 'nombre' => 'ARCABUCO'],
            ['departamento_id' => 5, 'codigo' => 87, 'nombre' => 'BELEN'],
            ['departamento_id' => 5, 'codigo' => 90, 'nombre' => 'BERBEO'],
            ['departamento_id' => 5, 'codigo' => 92, 'nombre' => 'BETEITIVA'],
            ['departamento_id' => 5, 'codigo' => 97, 'nombre' => 'BOAVITA'],
            ['departamento_id' => 5, 'codigo' => 104, 'nombre' => 'BOYACA'],
            ['departamento_id' => 5, 'codigo' => 106, 'nombre' => 'BRICEÑO'],
            ['departamento_id' => 5, 'codigo' => 109, 'nombre' => 'BUENAVISTA'],
            ['departamento_id' => 5, 'codigo' => 114, 'nombre' => 'BUSBANZA'],
            ['departamento_id' => 5, 'codigo' => 131, 'nombre' => 'CALDAS'],
            ['departamento_id' => 5, 'codigo' => 135, 'nombre' => 'CAMPOHERMOSO'],
            ['departamento_id' => 5, 'codigo' => 162, 'nombre' => 'CERINZA'],
            ['departamento_id' => 5, 'codigo' => 172, 'nombre' => 'CHINAVITA'],
            ['departamento_id' => 5, 'codigo' => 176, 'nombre' => 'CHIQUINQUIRA'],
            ['departamento_id' => 5, 'codigo' => 180, 'nombre' => 'CHISCAS'],
            ['departamento_id' => 5, 'codigo' => 183, 'nombre' => 'CHITA'],
            ['departamento_id' => 5, 'codigo' => 185, 'nombre' => 'CHITARAQUE'],
            ['departamento_id' => 5, 'codigo' => 187, 'nombre' => 'CHIVATA'],
            ['departamento_id' => 5, 'codigo' => 189, 'nombre' => 'CIENEGA'],
            ['departamento_id' => 5, 'codigo' => 204, 'nombre' => 'COMBITA'],
            ['departamento_id' => 5, 'codigo' => 212, 'nombre' => 'COPER'],
            ['departamento_id' => 5, 'codigo' => 215, 'nombre' => 'CORRALES'],
            ['departamento_id' => 5, 'codigo' => 218, 'nombre' => 'COVARACHIA'],
            ['departamento_id' => 5, 'codigo' => 223, 'nombre' => 'CUBARA'],
            ['departamento_id' => 5, 'codigo' => 224, 'nombre' => 'CUCAITA'],
            ['departamento_id' => 5, 'codigo' => 226, 'nombre' => 'CUITIVA'],
            ['departamento_id' => 5, 'codigo' => 232, 'nombre' => 'CHIQUIZA'],
            ['departamento_id' => 5, 'codigo' => 236, 'nombre' => 'CHIVOR'],
            ['departamento_id' => 5, 'codigo' => 238, 'nombre' => 'DUITAMA'],
            ['departamento_id' => 5, 'codigo' => 244, 'nombre' => 'EL COCUY'],
            ['departamento_id' => 5, 'codigo' => 248, 'nombre' => 'EL ESPINO'],
            ['departamento_id' => 5, 'codigo' => 272, 'nombre' => 'FIRAVITOBA'],
            ['departamento_id' => 5, 'codigo' => 276, 'nombre' => 'FLORESTA'],
            ['departamento_id' => 5, 'codigo' => 293, 'nombre' => 'GACHANTIVA'],
            ['departamento_id' => 5, 'codigo' => 296, 'nombre' => 'GAMEZA'],
            ['departamento_id' => 5, 'codigo' => 299, 'nombre' => 'GARAGOA'],
            ['departamento_id' => 5, 'codigo' => 317, 'nombre' => 'GUACAMAYAS'],
            ['departamento_id' => 5, 'codigo' => 322, 'nombre' => 'GUATEQUE'],
            ['departamento_id' => 5, 'codigo' => 325, 'nombre' => 'GUAYATA'],
            ['departamento_id' => 5, 'codigo' => 332, 'nombre' => 'GUICAN'],
            ['departamento_id' => 5, 'codigo' => 362, 'nombre' => 'IZA'],
            ['departamento_id' => 5, 'codigo' => 367, 'nombre' => 'JENESANO'],
            ['departamento_id' => 5, 'codigo' => 368, 'nombre' => 'JERICO'],
            ['departamento_id' => 5, 'codigo' => 377, 'nombre' => 'LABRANZAGRANDE'],
            ['departamento_id' => 5, 'codigo' => 380, 'nombre' => 'LA CAPILLA'],
            ['departamento_id' => 5, 'codigo' => 401, 'nombre' => 'LA VICTORIA'],
            ['departamento_id' => 5, 'codigo' => 403, 'nombre' => 'LA UVITA'],
            ['departamento_id' => 5, 'codigo' => 407, 'nombre' => 'VILLA DE LEIVA'],
            ['departamento_id' => 5, 'codigo' => 425, 'nombre' => 'MACANAL'],
            ['departamento_id' => 5, 'codigo' => 442, 'nombre' => 'MARIPI'],
            ['departamento_id' => 5, 'codigo' => 455, 'nombre' => 'MIRAFLORES'],
            ['departamento_id' => 5, 'codigo' => 464, 'nombre' => 'MONGUA'],
            ['departamento_id' => 5, 'codigo' => 466, 'nombre' => 'MONGUI'],
            ['departamento_id' => 5, 'codigo' => 469, 'nombre' => 'MONIQUIRA'],
            ['departamento_id' => 5, 'codigo' => 476, 'nombre' => 'MOTAVITA'],
            ['departamento_id' => 5, 'codigo' => 480, 'nombre' => 'MUZO'],
            ['departamento_id' => 5, 'codigo' => 491, 'nombre' => 'NOBSA'],
            ['departamento_id' => 5, 'codigo' => 494, 'nombre' => 'NUEVO COLON'],
            ['departamento_id' => 5, 'codigo' => 500, 'nombre' => 'OICATA'],
            ['departamento_id' => 5, 'codigo' => 507, 'nombre' => 'OTANCHE'],
            ['departamento_id' => 5, 'codigo' => 511, 'nombre' => 'PACHAVITA'],
            ['departamento_id' => 5, 'codigo' => 514, 'nombre' => 'PAEZ'],
            ['departamento_id' => 5, 'codigo' => 516, 'nombre' => 'PAIPA'],
            ['departamento_id' => 5, 'codigo' => 518, 'nombre' => 'PAJARITO'],
            ['departamento_id' => 5, 'codigo' => 522, 'nombre' => 'PANQUEBA'],
            ['departamento_id' => 5, 'codigo' => 531, 'nombre' => 'PAUNA'],
            ['departamento_id' => 5, 'codigo' => 533, 'nombre' => 'PAYA'],
            ['departamento_id' => 5, 'codigo' => 537, 'nombre' => 'PAZ DEL RIO'],
            ['departamento_id' => 5, 'codigo' => 542, 'nombre' => 'PESCA'],
            ['departamento_id' => 5, 'codigo' => 550, 'nombre' => 'PISBA'],
            ['departamento_id' => 5, 'codigo' => 572, 'nombre' => 'PUERTO BOYACA'],
            ['departamento_id' => 5, 'codigo' => 580, 'nombre' => 'QUIPAMA'],
            ['departamento_id' => 5, 'codigo' => 599, 'nombre' => 'RAMIRIQUI'],
            ['departamento_id' => 5, 'codigo' => 600, 'nombre' => 'RAQUIRA'],
            ['departamento_id' => 5, 'codigo' => 621, 'nombre' => 'RONDON'],
            ['departamento_id' => 5, 'codigo' => 632, 'nombre' => 'SABOYA'],
            ['departamento_id' => 5, 'codigo' => 638, 'nombre' => 'SACHICA'],
            ['departamento_id' => 5, 'codigo' => 646, 'nombre' => 'SAMACA'],
            ['departamento_id' => 5, 'codigo' => 660, 'nombre' => 'SAN EDUARDO'],
            ['departamento_id' => 5, 'codigo' => 664, 'nombre' => 'SAN JOSE DE PARE'],
            ['departamento_id' => 5, 'codigo' => 667, 'nombre' => 'SAN LUIS DE GACENO'],
            ['departamento_id' => 5, 'codigo' => 673, 'nombre' => 'SAN MATEO'],
            ['departamento_id' => 5, 'codigo' => 676, 'nombre' => 'SAN MIGUEL DE SEMA'],
            ['departamento_id' => 5, 'codigo' => 681, 'nombre' => 'SAN PABLO DE BORBUR'],
            ['departamento_id' => 5, 'codigo' => 686, 'nombre' => 'SANTANA'],
            ['departamento_id' => 5, 'codigo' => 690, 'nombre' => 'SANTA MARIA'],
            ['departamento_id' => 5, 'codigo' => 693, 'nombre' => 'SANTA ROSA DE VITERBO'],
            ['departamento_id' => 5, 'codigo' => 696, 'nombre' => 'SANTA SOFIA'],
            ['departamento_id' => 5, 'codigo' => 720, 'nombre' => 'SATIVANORTE'],
            ['departamento_id' => 5, 'codigo' => 723, 'nombre' => 'SATIVASUR'],
            ['departamento_id' => 5, 'codigo' => 740, 'nombre' => 'SIACHOQUE'],
            ['departamento_id' => 5, 'codigo' => 753, 'nombre' => 'SOATA'],
            ['departamento_id' => 5, 'codigo' => 755, 'nombre' => 'SOCOTA'],
            ['departamento_id' => 5, 'codigo' => 757, 'nombre' => 'SOCHA'],
            ['departamento_id' => 5, 'codigo' => 759, 'nombre' => 'SOGAMOSO'],
            ['departamento_id' => 5, 'codigo' => 761, 'nombre' => 'SOMONDOCO'],
            ['departamento_id' => 5, 'codigo' => 762, 'nombre' => 'SORA'],
            ['departamento_id' => 5, 'codigo' => 763, 'nombre' => 'SOTAQUIRA'],
            ['departamento_id' => 5, 'codigo' => 764, 'nombre' => 'SORACA'],
            ['departamento_id' => 5, 'codigo' => 774, 'nombre' => 'SUSACON'],
            ['departamento_id' => 5, 'codigo' => 776, 'nombre' => 'SUTAMARCHAN'],
            ['departamento_id' => 5, 'codigo' => 778, 'nombre' => 'SUTATENZA'],
            ['departamento_id' => 5, 'codigo' => 790, 'nombre' => 'TASCO'],
            ['departamento_id' => 5, 'codigo' => 798, 'nombre' => 'TENZA'],
            ['departamento_id' => 5, 'codigo' => 804, 'nombre' => 'TIBANA'],
            ['departamento_id' => 5, 'codigo' => 806, 'nombre' => 'TIBASOSA'],
            ['departamento_id' => 5, 'codigo' => 808, 'nombre' => 'TINJACA'],
            ['departamento_id' => 5, 'codigo' => 810, 'nombre' => 'TIPACOQUE'],
            ['departamento_id' => 5, 'codigo' => 814, 'nombre' => 'TOCA'],
            ['departamento_id' => 5, 'codigo' => 816, 'nombre' => 'TOGUI'],
            ['departamento_id' => 5, 'codigo' => 820, 'nombre' => 'TOPAGA'],
            ['departamento_id' => 5, 'codigo' => 822, 'nombre' => 'TOTA'],
            ['departamento_id' => 5, 'codigo' => 832, 'nombre' => 'TUNUNGUA'],
            ['departamento_id' => 5, 'codigo' => 835, 'nombre' => 'TURMEQUE'],
            ['departamento_id' => 5, 'codigo' => 837, 'nombre' => 'TUTA'],
            ['departamento_id' => 5, 'codigo' => 839, 'nombre' => 'TUTASA'],
            ['departamento_id' => 5, 'codigo' => 842, 'nombre' => 'UMBITA'],
            ['departamento_id' => 5, 'codigo' => 861, 'nombre' => 'VENTAQUEMADA'],
            ['departamento_id' => 5, 'codigo' => 879, 'nombre' => 'VIRACACHA'],
            ['departamento_id' => 5, 'codigo' => 897, 'nombre' => 'ZETAQUIRA'],
            ['departamento_id' => 6, 'codigo' => 1, 'nombre' => 'MANIZALES'],
            ['departamento_id' => 6, 'codigo' => 13, 'nombre' => 'AGUADAS'],
            ['departamento_id' => 6, 'codigo' => 42, 'nombre' => 'ANSERMA'],
            ['departamento_id' => 6, 'codigo' => 50, 'nombre' => 'ARANZAZU'],
            ['departamento_id' => 6, 'codigo' => 88, 'nombre' => 'BELALCAZAR'],
            ['departamento_id' => 6, 'codigo' => 174, 'nombre' => 'CHINCHINA'],
            ['departamento_id' => 6, 'codigo' => 272, 'nombre' => 'FILADELFIA'],
            ['departamento_id' => 6, 'codigo' => 380, 'nombre' => 'LA DORADA'],
            ['departamento_id' => 6, 'codigo' => 388, 'nombre' => 'LA MERCED'],
            ['departamento_id' => 6, 'codigo' => 433, 'nombre' => 'MANZANARES'],
            ['departamento_id' => 6, 'codigo' => 442, 'nombre' => 'MARMATO'],
            ['departamento_id' => 6, 'codigo' => 444, 'nombre' => 'MARQUETALIA'],
            ['departamento_id' => 6, 'codigo' => 446, 'nombre' => 'MARULANDA'],
            ['departamento_id' => 6, 'codigo' => 486, 'nombre' => 'NEIRA'],
            ['departamento_id' => 6, 'codigo' => 495, 'nombre' => 'NORCASIA'],
            ['departamento_id' => 6, 'codigo' => 513, 'nombre' => 'PACORA'],
            ['departamento_id' => 6, 'codigo' => 524, 'nombre' => 'PALESTINA'],
            ['departamento_id' => 6, 'codigo' => 541, 'nombre' => 'PENSILVANIA'],
            ['departamento_id' => 6, 'codigo' => 614, 'nombre' => 'RIOSUCIO'],
            ['departamento_id' => 6, 'codigo' => 616, 'nombre' => 'RISARALDA'],
            ['departamento_id' => 6, 'codigo' => 653, 'nombre' => 'SALAMINA'],
            ['departamento_id' => 6, 'codigo' => 662, 'nombre' => 'SAMANA'],
            ['departamento_id' => 6, 'codigo' => 665, 'nombre' => 'SAN JOSE'],
            ['departamento_id' => 6, 'codigo' => 777, 'nombre' => 'SUPIA'],
            ['departamento_id' => 6, 'codigo' => 867, 'nombre' => 'VICTORIA'],
            ['departamento_id' => 6, 'codigo' => 873, 'nombre' => 'VILLAMARIA'],
            ['departamento_id' => 6, 'codigo' => 877, 'nombre' => 'VITERBO'],
            ['departamento_id' => 7, 'codigo' => 1, 'nombre' => 'FLORENCIA'],
            ['departamento_id' => 7, 'codigo' => 29, 'nombre' => 'ALBANIA'],
            ['departamento_id' => 7, 'codigo' => 94, 'nombre' => 'BELEN DE LOS ANDAQUIES'],
            ['departamento_id' => 7, 'codigo' => 150, 'nombre' => 'CARTAGENA DEL CHAIRA'],
            ['departamento_id' => 7, 'codigo' => 205, 'nombre' => 'CURILLO'],
            ['departamento_id' => 7, 'codigo' => 247, 'nombre' => 'EL DONCELLO'],
            ['departamento_id' => 7, 'codigo' => 256, 'nombre' => 'EL PAUJIL'],
            ['departamento_id' => 7, 'codigo' => 410, 'nombre' => 'LA MONTAÑITA'],
            ['departamento_id' => 7, 'codigo' => 460, 'nombre' => 'MILAN'],
            ['departamento_id' => 7, 'codigo' => 479, 'nombre' => 'MORELIA'],
            ['departamento_id' => 7, 'codigo' => 592, 'nombre' => 'PUERTO RICO'],
            ['departamento_id' => 7, 'codigo' => 610, 'nombre' => 'SAN JOSE DE FRAGUA'],
            ['departamento_id' => 7, 'codigo' => 753, 'nombre' => 'SAN VICENTE DEL CAGUAN'],
            ['departamento_id' => 7, 'codigo' => 756, 'nombre' => 'SOLANO'],
            ['departamento_id' => 7, 'codigo' => 785, 'nombre' => 'SOLITA'],
            ['departamento_id' => 7, 'codigo' => 860, 'nombre' => 'VALPARAISO'],
            ['departamento_id' => 8, 'codigo' => 1, 'nombre' => 'POPAYAN'],
            ['departamento_id' => 8, 'codigo' => 22, 'nombre' => 'ALMAGUER'],
            ['departamento_id' => 8, 'codigo' => 50, 'nombre' => 'ARGELIA'],
            ['departamento_id' => 8, 'codigo' => 75, 'nombre' => 'BALBOA'],
            ['departamento_id' => 8, 'codigo' => 100, 'nombre' => 'BOLIVAR'],
            ['departamento_id' => 8, 'codigo' => 110, 'nombre' => 'BUENOS AIRES'],
            ['departamento_id' => 8, 'codigo' => 130, 'nombre' => 'CAJIBIO'],
            ['departamento_id' => 8, 'codigo' => 137, 'nombre' => 'CALDONO'],
            ['departamento_id' => 8, 'codigo' => 142, 'nombre' => 'CALOTO'],
            ['departamento_id' => 8, 'codigo' => 212, 'nombre' => 'CORINTO'],
            ['departamento_id' => 8, 'codigo' => 256, 'nombre' => 'EL TAMBO'],
            ['departamento_id' => 8, 'codigo' => 290, 'nombre' => 'FLORENCIA'],
            ['departamento_id' => 8, 'codigo' => 318, 'nombre' => 'GUAPI'],
            ['departamento_id' => 8, 'codigo' => 355, 'nombre' => 'INZA'],
            ['departamento_id' => 8, 'codigo' => 364, 'nombre' => 'JAMBALO'],
            ['departamento_id' => 8, 'codigo' => 392, 'nombre' => 'LA SIERRA'],
            ['departamento_id' => 8, 'codigo' => 397, 'nombre' => 'LA VEGA'],
            ['departamento_id' => 8, 'codigo' => 418, 'nombre' => 'LOPEZ (MICAY)'],
            ['departamento_id' => 8, 'codigo' => 450, 'nombre' => 'MERCADERES'],
            ['departamento_id' => 8, 'codigo' => 455, 'nombre' => 'MIRANDA'],
            ['departamento_id' => 8, 'codigo' => 473, 'nombre' => 'MORALES'],
            ['departamento_id' => 8, 'codigo' => 513, 'nombre' => 'PADILLA'],
            ['departamento_id' => 8, 'codigo' => 517, 'nombre' => 'PAEZ (BELALCAZAR)'],
            ['departamento_id' => 8, 'codigo' => 532, 'nombre' => 'PATIA (EL BORDO)'],
            ['departamento_id' => 8, 'codigo' => 533, 'nombre' => 'PIAMONTE'],
            ['departamento_id' => 8, 'codigo' => 548, 'nombre' => 'PIENDAMO'],
            ['departamento_id' => 8, 'codigo' => 573, 'nombre' => 'PUERTO TEJADA'],
            ['departamento_id' => 8, 'codigo' => 585, 'nombre' => 'PURACE (COCONUCO)'],
            ['departamento_id' => 8, 'codigo' => 622, 'nombre' => 'ROSAS'],
            ['departamento_id' => 8, 'codigo' => 693, 'nombre' => 'SAN SEBASTIAN'],
            ['departamento_id' => 8, 'codigo' => 698, 'nombre' => 'SANTANDER DE QUILICHAO'],
            ['departamento_id' => 8, 'codigo' => 701, 'nombre' => 'SANTA ROSA'],
            ['departamento_id' => 8, 'codigo' => 743, 'nombre' => 'SILVIA'],
            ['departamento_id' => 8, 'codigo' => 760, 'nombre' => 'SOTARA (PAISPAMBA)'],
            ['departamento_id' => 8, 'codigo' => 780, 'nombre' => 'SUAREZ'],
            ['departamento_id' => 8, 'codigo' => 807, 'nombre' => 'TIMBIO'],
            ['departamento_id' => 8, 'codigo' => 809, 'nombre' => 'TIMBIQUI'],
            ['departamento_id' => 8, 'codigo' => 821, 'nombre' => 'TORIBIO'],
            ['departamento_id' => 8, 'codigo' => 824, 'nombre' => 'TOTORO'],
            ['departamento_id' => 8, 'codigo' => 845, 'nombre' => 'VILLARICA'],
        ];

        foreach ($municipios as $municipio) {
            Municipio::create($municipio);
        }
    }
}
